package com.grind.statistics.enums;

public enum StatisticsMessageType {
    GET_TRACK_COMPLETION,
    GET_TRACK_REMAINING_LOAD,
    GET_TRACK_OVERDUE_PRESSURE,
    GET_TRACK_ACTIVE_TASKS_AGING,
    GET_TRACK_WORK_IN_PROGRESS,
    GET_TRACK_OVERDUE_AMONG_COMPLETED,

    GET_SPRINT_COMPLETION,
    GET_SPRINT_REMAINING_LOAD,
    GET_SPRINT_OVERDUE_PRESSURE,
    GET_SPRINT_ACTIVE_TASKS_AGING,
    GET_SPRINT_WORK_IN_PROGRESS,
    GET_SPRINT_OVERDUE_AMONG_COMPLETED,

    GET_COMPLETED_LAST_MONTH,
    GET_COMPLETED_LAST_WEEK,

    TRACK_COMPLETION,
    TRACK_REMAINING_LOAD,
    TRACK_OVERDUE_PRESSURE,
    TRACK_ACTIVE_TASKS_AGING,
    TRACK_WORK_IN_PROGRESS,
    TRACK_OVERDUE_AMONG_COMPLETED,

    SPRINT_COMPLETION,
    SPRINT_REMAINING_LOAD,
    SPRINT_OVERDUE_PRESSURE,
    SPRINT_ACTIVE_TASKS_AGING,
    SPRINT_WORK_IN_PROGRESS,
    SPRINT_OVERDUE_AMONG_COMPLETED,

    COMPLETED_LAST_MONTH,
    COMPLETED_LAST_WEEK,

    ERROR
}
