package com.grind.statistics.enums;

public enum StatisticsMessageType {
    GET_TRACK_STATS_ACTUAL_STATE,
    GET_TRACK_STATS_RAW,
    GET_SPRINT_STATS,
    GET_STATS_PER_WEEK,
    GET_STATS_PER_DAY,
    GET_STATS_PER_WEEK_IN_RANGE,
    GET_STATS_PER_DAY_IN_RANGE,

    TRACK_STATS_ACTUAL_STATE,
    TRACK_STATS_RAW,
    SPRINT_STATS,
    STATS_PER_WEEK,
    STATS_PER_DAY,
    STATS_PER_WEEK_IN_RANGE,
    STATS_PER_DAY_IN_RANGE,

    SYNC_DATABASES,
    DATABASES_SYNCED,
    RETRIEVE_POSTGRES,
    POSTGRES_RETRIEVED,
    ERROR
}
