package com.grind.template.enums;

public enum TemplateMessageType {
    GET_TEMPLATE,
    GET_PUBLIC_TEMPLATES,
    GET_TEMPLATES_OF_AUTHOR,
    GET_TEMPLATES_OF_CATEGORY,
    ARCHIVE_TEMPLATE,
    PUBLISH_TEMPLATE,
    CREATE_TEMPLATE,
    EDIT_TEMPLATE,
    TEMPLATE_APPLICATION_REQUEST,

    TEMPLATE,
    PUBLIC_TEMPLATES,
    TEMPLATES_OF_AUTHOR,
    TEMPLATES_OF_CATEGORY,
    TEMPLATE_PUBLISHED,
    TEMPLATE_ARCHIVED,
    TEMPLATE_CREATED,
    TEMPLATE_EDITED,
    APPLY_TEMPLATE,

    UNDEFINED,
    ERROR
}
