package com.grind.gateway.enums;

public enum CoreMessageType {
    // TRACK RELATED

    GET_TRACK,
    GET_TRACKS_OF_USER,
    GET_ALL_TRACKS,
    GET_SPRINTS_OF_TRACK,
    CREATE_TRACK,
    CHANGE_TRACK,
    DELETE_TRACK,

    // TASK RELATED

    GET_TASKS_OF_TRACK,
    GET_TASKS_OF_SPRINT,
    GET_TASK,
    GET_ALL_TASKS,
    CREATE_TASK,
    CHANGE_TASK,
    PLAN_TASK_DATE,
    PLAN_TASK_SPRINT,
    COMPLETE_TASK,
    MOVE_TASK_TO_BACKLOG,
    DELETE_TASK,

    UNDEFINED,
    ERROR
}
