package com.grind.gateway.enums;

public enum StatisticsMessageType {
    GET_TRACK_STATS_ACTUAL_STATE,
    GET_TRACK_STATS_RAW,
    GET_SPRINT_STATS,

    GET_SPRINT_COMPLETION,
    GET_SPRINT_REMAINING_LOAD,
    GET_SPRINT_OVERDUE_PRESSURE,
    GET_SPRINT_ACTIVE_TASKS_AGING,
    GET_SPRINT_WORK_IN_PROGRESS,
    GET_SPRINT_OVERDUE_AMONG_COMPLETED,


    TRACK_STATS_ACTUAL_STATE,
    TRACK_STATS_RAW,



    ERROR
}
